### ISSUE TITLE
Lab does not work for Mac OS Big Sur users

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-mongodb-lab#4]
The lab needs alternative lessons for Mac OS Big Sur users, who are unable to create data/db in the specified location (is a read-only location). Suggest updating or revising to some solution similar to below using alias and new location. 

https://medium.com/nerd-for-tech/how-to-install-mongodb-on-macos-big-sur-d6df6ac69618

**Comment by christine-egan42** [comment]
Creating a solution to address this issue with more specific instructions for each OS. Will also solve the issues below:

- https://github.com/learn-co-curriculum/dsc-mongodb/issues/4
- https://github.com/learn-co-curriculum/dsc-mongodb/issues/5
- https://github.com/learn-co-curriculum/dsc-mongodb/issues/6

**Comment by bpurdy-ds** [comment]
With the further updates to the Mac OS, learn environments, etc., we can close this.
