### ISSUE TITLE
Instructions require URI and Certificate TLS in the solution

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-mongodb-lab#6]
The following is not taught in the preceding lessons (uses a different method) and is confusing for students. It is not explained how to find (1) the URI or (2) the TLS certificate, which the lesson didn't required. This should be revised. 

MongoDB Atlas database URI and the path on your local computer to your TLS Certificate. Dont forget quotes!

**Comment by bpurdy-ds** [comment]
Hello. Sorry for the very long delay.
1. This content is no longer part of the standard curriculum.
2. It may eventually return as a Phase 6 topic.
3. The part that is not taught is in the solution that the student has access to.
Given (1) - (3), we'll close the issue leaving the status quo.

**Comment by bpurdy-ds** [comment]
Hello. Sorry for the very long delay.
1. This content is no longer part of the standard curriculum.
2. It may eventually return as a Phase 6 topic.
3. The part that is not taught is in the solution that the student has access to.
Given (1) - (3), we'll close the issue leaving the status quo.
